# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
name = "Blog"
url = "/post"
weight = 1

[[main]]
name = "Higher Ed + Data Science Consulting"
url = "/consulting"
weight = 3

[[main]]
name = "Presentations and Talks"
url = "/talk"
weight = 2

[[main]]
name = "Projects"
url = "/project"
weight = 4

#[[main]]
#name = "Publications"
#url = "#featured"
#weight = 40

[[main]]
name = "Contact"
url = "#contact"
weight = 5

#Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
name = "CV/Resume"
url = "files/weiner_brad_resume.pdf"
weight = 6
